In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
# a = np.array([1, 2, 3], dtype='int16') dtypewill specify the memory for each element. 
print(a)

[1 2 3]


In [3]:
mylist = [1, 2, 3]
myarray = np.array(mylist)  #converting a list to a numpy array

In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimensions
b.ndim

2

In [6]:
# Get Shape
#a.shape = 3
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Total number of elements in the array
b.size

6

## Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c], you can access using negatives as well
a[1, 3]

11

In [12]:
# Get a specific row 
a[0, :]   #this would return the first row

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2] #this would return the third column

array([ 3, 10])

In [14]:

# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])   # startindex = 2, endindex = 6, stepsize = 2 (everyother)
print(a[0, 1:-1:2])    #the 

[2 4 6]
[2 4 6]


In [15]:
a[1,5] = 20 #updating a specific element

a[:,2] = [1,2] #update the column to whatever we want. this would changed the third column to alternate 1s and 2s. 
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1] # 0 = first set, 1 = 2nd row, 1 = 2nd column

4

In [18]:
# replace 
b[:,1,:] = [[9,9],[8,8]]  #as long as this is the same deminsion this will work

In [19]:
a[0, :].reshape(7, 1) #this pulls the first row of the a matrix then reshapes it to a vertical array

array([[1],
       [2],
       [1],
       [4],
       [5],
       [6],
       [7]])

In [61]:
#grabbing the first 2x2 block
print(a[0:2, 0:2])   #we can assign this slice to new values if we wanted [0:2, 0:2] = 5
 

[[1. 1.]
 [1. 1.]]


#### small matrix math example

In [104]:
A = np.array([[1, 2, 3, 4], 
             [5, 6, 7, 8], 
             [2, 4, 6, 8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [105]:
cal = A.sum(axis=0)   #summing the columns, axis=1 is row
print(cal)

[ 8 12 16 20]


In [108]:
percentage = 100 * A / cal
print(percentage)        # returns the percentage of each element as each columns was added up

[[12.5        16.66666667 18.75       20.        ]
 [62.5        50.         43.75       40.        ]
 [25.         33.33333333 37.5        40.        ]]


## Initializing Different Types of Arrays

In [62]:
#  All 0s matrix
zeros = np.zeros((2,3)) # 2 rows, 3 columns
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [63]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [64]:
# Any other number
np.full((2,2), 99, dtype='float32')   #creating an array for any number you want, dtype is optional

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [65]:
# Any other number (full_like)
np.full_like(a, 4)   #this updates the array 'a' to the number specified

array([[4., 4., 4.],
       [4., 4., 4.]])

In [66]:
# Random decimal numbers
np.random.random_sample(a.shape)  # this will return random values between 0 and 1 in an array the same shape as a
np.random.rand(4,2)

array([[0.18696743, 0.9943179 ],
       [0.5206654 , 0.57878954],
       [0.73481906, 0.54196177],
       [0.91315356, 0.80792015]])

In [67]:
np.arange(0, 10, 2)  #creates a range of data. the 3rd element is the step size

array([0, 2, 4, 6, 8])

In [68]:
np.random.seed(101)                #This allows folks to create "random" arrays that will be the same. the seed # must be same
arr = np.random.randint(0, 100, 10)

In [69]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [70]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [71]:
print(arr.max()) #will return the max value
print(arr.argmax())  #will return the index of the max value position
print(arr.min()) #will return the min value
print(arr.argmin())  #will return the index of the min value position

95
0
9
7


In [72]:
arr.mean() #will return the mean

60.8

In [73]:
arr.reshape((2, 5))  #will reshape to the layout you want. must be the same amount of elements as before.

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [74]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))  #will return values between -4 and 8 in an array of 3 x 3

array([[-3, -1,  6],
       [ 4, -1, -1],
       [ 7, -2,  4]])

In [75]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis =0)  #axis = 0 is optional. this will repeat the array on the 0th axis. be sure to have the array
                                                        #in 2 deminsions [[1,2,3]]  (2 brackets)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [77]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [79]:
#challenge. make a 5x5 box with a 9 in the middle surronded by 0, then surrounded by 1s. 

ans = np.zeros((5,5))
ans[0, :] = 1   #changing the first row to one
ans[-1, :] = 1
ans[:, 0] = 1
ans[:, -1] = 1
ans[2, 2] = 9

print(ans)


# or

output = np.ones((5, 5))
z = np.zeros((3, 3))
z[1, 1] = 9
output[1:-1, 1:-1] = z  #highlighting the 3x3 section in the middle of the 5x5 array then replacing it with z
print('')
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [80]:
a = np.array([1, 2, 3])
b = a.copy()                  #using the a.copy() will copy the content from 'a' but now we can treat/alter the variable b 
                              # as its own independent variable without manipulating a as well
b[0] = 100
print(a)

[1 2 3]


## Mathematics 

In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a + 2

array([3, 4, 5, 6])

In [83]:

a - 2

array([-1,  0,  1,  2])

In [84]:
a * 2

array([2, 4, 6, 8])

In [85]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [86]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [87]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [88]:
# Take the sin
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## Linear Algebra

In [90]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [91]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [92]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [93]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.min(stats)


1

In [95]:
np.max(stats, axis=1)


array([3, 6])

In [96]:
np.sum(stats, axis=0)


array([5, 7, 9])

## Reorganizing Arrays

In [97]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8, 1))   
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [98]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])   #will stack the array on top of one another, will return an output of 1 array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Loading Data

In [100]:
#filedata = np.genfromtxt('data.txt', delimiter = ',')   #creating an array and separating the values with a comma
#filedata.astype('int32')                                #numbers will come in a float, use this to change to integer

### Boolean Masking and Advanced Indexing


In [102]:
#(~((filedata > 50) & (filedata < 100)))

### Reducing Bugs

In [110]:
a = np.random.randn(1, 5) #add the second number to specify the matrix shape
print(a)

# dont use a = np.random.randn(5) "this is called a rank 1 array"

[[ 0.68350889  0.30266545  1.69372293 -1.70608593 -1.15911942]]


In [111]:
a.shape

(1, 5)

In [118]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)

In [119]:
c = a * b
c.shape

(3, 3)